#!/usr/bin/env ruby

require 'pg'
require 'rom-repository'
require 'rom-sql'

require './settings'
require './lib/panadoura/rom_config'
require './lib/panadoura/migrations'

# create the database first
conn = PG::Connection.open(dbname: 'postgres', host: ENV['DB_HOST'], user: ENV['DB_USER'], password: ENV['DB_PASSWORD'])
conn.exec("CREATE DATABASE #{ENV['DB_DATABASE']}")

# create the tables
Panadoura.migrate
